<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.csagent</groupId>
        <artifactId>csagent-modules</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>csagent-application</artifactId>

    <description>
        应用模块
    </description>

    <dependencies>

        <!-- 通用工具-->
        <dependency>
            <groupId>com.csagent</groupId>
            <artifactId>csagent-common-core</artifactId>
        </dependency>

        <dependency>
            <groupId>com.csagent</groupId>
            <artifactId>csagent-common-doc</artifactId>
        </dependency>

        <dependency>
            <groupId>com.csagent</groupId>
            <artifactId>csagent-common-sms</artifactId>
        </dependency>

        <dependency>
            <groupId>com.csagent</groupId>
            <artifactId>csagent-common-mail</artifactId>
        </dependency>

        <dependency>
            <groupId>com.csagent</groupId>
            <artifactId>csagent-common-redis</artifactId>
        </dependency>

        <dependency>
            <groupId>com.csagent</groupId>
            <artifactId>csagent-common-idempotent</artifactId>
        </dependency>

        <dependency>
            <groupId>com.csagent</groupId>
            <artifactId>csagent-common-mybatis</artifactId>
        </dependency>

        <dependency>
            <groupId>com.csagent</groupId>
            <artifactId>csagent-common-log</artifactId>
        </dependency>

        <dependency>
            <groupId>com.csagent</groupId>
            <artifactId>csagent-common-excel</artifactId>
        </dependency>

        <dependency>
            <groupId>com.csagent</groupId>
            <artifactId>csagent-common-security</artifactId>
        </dependency>

        <dependency>
            <groupId>com.csagent</groupId>
            <artifactId>csagent-common-web</artifactId>
        </dependency>

        <dependency>
            <groupId>com.csagent</groupId>
            <artifactId>csagent-common-ratelimiter</artifactId>
        </dependency>

        <dependency>
            <groupId>com.csagent</groupId>
            <artifactId>csagent-common-translation</artifactId>
        </dependency>

        <dependency>
            <groupId>com.csagent</groupId>
            <artifactId>csagent-common-sensitive</artifactId>
        </dependency>

        <dependency>
            <groupId>com.csagent</groupId>
            <artifactId>csagent-common-encrypt</artifactId>
        </dependency>

        <dependency>
            <groupId>com.csagent</groupId>
            <artifactId>csagent-common-tenant</artifactId>
        </dependency>

        <dependency>
            <groupId>com.csagent</groupId>
            <artifactId>csagent-common-websocket</artifactId>
        </dependency>

        <dependency>
            <groupId>com.csagent</groupId>
            <artifactId>csagent-common-langchain4j</artifactId>
        </dependency>

        <dependency>
            <groupId>com.csagent</groupId>
            <artifactId>csagent-knowledge</artifactId>
        </dependency>

        <dependency>
            <groupId>com.csagent</groupId>
            <artifactId>csagent-model</artifactId>
        </dependency>




    </dependencies>


</project>
