<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>Customer-Service-Agent</artifactId>
        <groupId>com.csagent</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <modules>
        <module>csagent-application</module>
        <module>csagent-demo</module>
        <module>csagent-generator</module>
        <module>csagent-job</module>
        <module>csagent-system</module>
        <module>csagent-workflow</module>
        <module>csagent-model</module>
        <module>csagent-knowledge</module>
    </modules>

    <artifactId>csagent-modules</artifactId>
    <packaging>pom</packaging>

    <description>
        csagent-modules 业务模块
    </description>

</project>
